USE [Pottencial]
GO

/****** Object:  Table [dbo].[Venda]    Script Date: 31/05/2022 07:33:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Venda](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DataVenda] [datetime] NOT NULL,
	[StatusVenda] [int] NOT NULL,
	[VendedorId] [int] NOT NULL,
 CONSTRAINT [PK_Venda] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Venda]  WITH CHECK ADD  CONSTRAINT [FK_Venda_Vendedor] FOREIGN KEY([VendedorId])
REFERENCES [dbo].[Vendedor] ([Id])
GO

ALTER TABLE [dbo].[Venda] CHECK CONSTRAINT [FK_Venda_Vendedor]
GO


